name: fcre-generate-graphs

# Controls when the action will run.
on: 
  schedule:
    - cron: '00 07 * * *'

jobs: 
  generate-graphs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Load repo and install R
    steps:
      - name: Checkout with fcre-generate-graphs branch
        uses: actions/checkout@v2
        with:
          ref: fcre-generate-graphs
          fetch-depth: 1

      - name: Set Up R
        uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: |
          R -e 'install.packages("lubridate")'
      - name: Run R Script
        run: Rscript fcre-generate-graphs.R
      
      # Commit files ,and push
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add WeirDataFigures_$(date '+%Y-%m-%d').pdf MetDataFigures_$(date '+%Y-%m-%d').pdf BVRDataFigures_$(date '+%Y-%m-%d').pdf \
          FCRCatwalkDataFigures_$(date '+%Y-%m-%d').pdf CCRMetDataFigures_$(date '+%Y-%m-%d').pdf CCRWaterQualityDataFigures_$(date '+%Y-%m-%d').pdf
          git commit -m "fcre-generate-graphs-$(date '+%Y-%m-%d')"
          git branch fcre-graphs
          git push --force origin fcre-graphs
