name: QAQC catwalk data
on:
   workflow_dispatch:
   schedule:
   - cron: "0 2 * * *"

jobs:
  qaqc_run:
     runs-on: ubuntu-latest
     container:
      image: rocker/tidyverse:latest
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
         with:
           ref: fcre-catwalk-data
           fetch-depth: 1
       - name: Run QAQC script
         run:  | 
           R -e 'install.packages(c("EDIutils","xml2","here"))'
           Rscript $GITHUB_WORKSPACE/R/QAQC_workflow.R
       - name: Commit files
         run: |
            git config --global --add safe.directory $GITHUB_WORKSPACE
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add fcre-waterquality_L1.csv
            git commit -m "Updating QAQC file" || echo "No changes to commit"
            git push || echo "No changes to commit"
