name: QAQC catwalk data
on:
   push:
      branches: [ fcre-catwalk-data ]
      #paths: 
      #- 'fcre-waterquality.csv'
   workflow_dispatch:

jobs:
  qaqc_run:
     runs-on: ubuntu-latest
     container:
      image: rocker/tidyverse:latest
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
         with:
           ref: fcre-catwalk-data-qaqc
           fetch-depth: 1
       - name: Download necessary files
         run: |
            wget -N https://raw.githubusercontent.com/FLARE-forecast/FCRE-data/fcre-catwalk-data/fcre-waterquality.csv
       - name: Run QAQC script
         run: | 
           R -e 'install.packages(c("EDIutils","xml2","here","suncalc"))'
           Rscript $GITHUB_WORKSPACE/R/QAQC_workflow.R
       - name: Configure Git
         run: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
       - name: Commit files
         run: |
            git add fcre-waterquality_L1.csv
            git commit -m "Updating QAQC files" || echo "No changes to commit"
            git push || echo "No changes to commit"
