on:
   workflow_dispatch:
   #schedule:
   #- cron: "0 2 * * *"

jobs:
  qaqc_run:
     runs-on: ubuntu-latest
     container:
      image: rocker/tidyverse:latest
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
         with:
           ref: fcre-catwalk-data
           fetch-depth: 1

 # run the QAQC workflow
       - name: Run QAQC script
         run:  | 
           Rscript $GITHUB_WORKSPACE/R/QAQC_workflow.R
       - name: Commit files
         run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add fcre-waterquality_L1.csv
            git commit -m "Updating QAQC file"
            git push
