name: QAQC catwalk data
on:
  push:
    branches: [ fcre-catwalk-data ]
    # paths:
    # - 'fcre-waterquality.csv'
  workflow_dispatch:

jobs:
  qaqc_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: fcre-catwalk-data
          fetch-depth: 1

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v1

      - name: Install R dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev
          R -e 'install.packages(c("EDIutils", "xml2", "here"))'

      - name: Run QAQC script
        run: Rscript R/QAQC_workflow.R

      - name: Checkout qaqc-data branch
        uses: actions/checkout@v3
        with:
          ref: qaqc-data
          clean: false

      - name: Commit files
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add fcre-waterquality_L1.csv
          git commit -m "Updating QAQC file" || echo "No changes to commit"
          git push -u origin qaqc-data || echo "No changes to commit"
