name: GitHub Monitor
on:
  push:
    branches:
      - fcre-metstation-data
  schedule:
    - cron: "* * * * *" #Check every 6 hours
jobs:
   
  Commit-Time-Calculation:
    runs-on: ubuntu-latest
    steps:     
      - name: Check for commits within time 
        uses: AlexHolderDeveloper/CommitsWithinTime@v1.1.5
        id: commitswithintime
        with:
          hours: 6

      - name: Get the output from CommitsWithinTime
        run:
          echo "The 'has-new-commits-within-time' value is ${{ steps.commitswithintime.outputs.has-new-commits-within-time }}"
          echo "The 'number-of-commits-within-time' value is ${{ steps.commitswithintime.outputs.number-of-commits-within-time }}"
          echo "The 'total-commits' value is ${{ steps.commitswithintime.outputs.total-commits }}"
  
  Send-Up-Messages-Actions:
    needs: Commit-Time-Calculation
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.0.0
        id: send-message

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C029BRRA6KA
          slack-text: Up!

      - name: Send Slack Message Result
        run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"

  Send-Down-Messages-Actions:
    needs: Commit-Time-Calculation
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.0.0
        id: send-message

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C029BRRA6KA
          slack-text: Down!

      - name: Send Slack Message Result
        run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"

