name: GitHub Monitor
on:
  push:
    branches:
      - fcre-metstation-data
  schedule:
    - cron: "* */6 * * *" #Check every 6 hours
jobs:
  Commit-Time-Calculation:
    runs-on: ubuntu-latest
    steps:
      env:
        SEND_MESSAGE: False
        MAXIMUM_WINDOW: 22800
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
        run: CURRENT_TIME=$(date +%s)
        run: LAST_COMMIT=$(curl https://api.github.com/repos/FLARE-forecast/FCRE-data/commits/${fcre-metstation-data} 2>&1 | grep '"date"' | tail -n 1 | sed 's/.*\ //' | sed -e 's/^"//' -e 's/"$//')
        run: echo $LAST_COMMIT
        run: LAST_COMMIT_EPOCH=$(date "+%s" -d ${LAST_COMMIT})
        run: echo $LAST_COMMIT_EPOCH
        run: echo $SEND_MESSAGE
  
  Send-Up-Messages-Actions:
    if: SEND_MESSAGE == 'True'
    needs: Commit-Time-Calculation
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.0.0
        id: send-message

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C029BRRA6KA
          slack-text: Up!

      - name: Send Slack Message Result
        run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"

  Send-Down-Messages-Actions:
    if: SEND_MESSAGE == 'False'
    needs: Commit-Time-Calculation
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.0.0
        id: send-message

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C029BRRA6KA
          slack-text: Down!

      - name: Send Slack Message Result
        run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"

