name: wvwa-generate-graphs

on:
  schedule:
    - cron: '00 06 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Graphs"]
    types:
      - completed

jobs: 
  generate-graphs:
    runs-on: ubuntu-latest
    steps:
      - name: Retry wrapper
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error # can be "error" or "failure"
          command: |
            git clone --branch wvwa-generate-graphs [Your Repo URL]
            R -e 'install.packages("lubridate")'
            Rscript wvwa-generate-graphs.R
            # ... your other steps for commit and push ...

  send-mail:
    needs: generate-graphs
    if: always() && needs.generate-graphs.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: |
            ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            The workflow link is https://github.com/FLARE-forecast/FCRE-data/actions/runs/${{ github.run_id }}
          to: abreefpilz@vt.edu, vdaneshmand@acis.ufl.edu
          from: FLARE
